### ISSUE TITLE
BS12のスキャン結果について

### ISSUE THREAD

**Issue by Tokman5** [tsukumijima/ISDBScanner#2]
環境：Ubuntu Server LTS 24.04
ISDBScannerでのスキャン結果から生成されたファイルをMirakurunなどのセットアップに使用しましたが、Mirakurunの管理画面チャンネル一覧でBS12が表示されていないことに気づきました。
スキャンに使ったのはDTV02A-1T1S-Uです。生成されたChannels.jsonからBS12に関する部分を抜き出しました。
```json
{
    "physical_channel": "BS09/TS1",
    "transport_stream_id": 16530,
    "network_id": 4,
    "network_name": "BS Digital",
    "remote_control_key_id": null,
    "satellite_frequency": 11.88092,
    "satellite_transponder": 9,
    "satellite_slot_number": 1,
    "services": [
        {
            "channel_number": "222",
            "service_id": 222,
            "service_type": 1,
            "service_name": "BS12トゥエルビ",
            "is_free": true,
            "is_oneseg": false
        }
    ],
    "broadcast_type": "BS",
    "physical_channel_recisdb": "BS09_1",
    "physical_channel_recpt1": "BS09_1"
},
```
他の人がアップロードしているMirakurunのチャンネル設定ファイルなどと比べると、`BS09/TS1`や`BS09_1`の1が、本当は2になるはずだと思われます。`BS09_1`はかつてスターチャンネル1が入っていたところのようです。
Mirakurunのchannels.ymlの該当する部分を編集すると正しくチャンネルが認識されるようになりました。

**Comment by tsukumijima** [comment]
@Tokman5 
ご報告ありがとうございます…！ 普段 BS12 を見ないものですから気づきませんでした…。
原因は仰る通りスターチャンネル1の閉局で、ひとまずワークアラウンドを導入した v1.1.4 にて修正してあります。
ISDBScanner v1.1.4 で再度チャンネルスキャンを行えば、正常に BS12 の物理チャンネルが BS09_2 として記載されるはずです…！

重ね重ねありがとうございました…！
https://github.com/tsukumijima/ISDBScanner/releases/tag/v1.1.4
