### ISSUE TITLE
DD Max M4でエラーになる

### ISSUE THREAD

**Issue by daisukekoba** [tsukumijima/ISDBScanner#3]
Ubuntu Server 24.04 (x86_64) で DD Max M4 を接続した環境で実行するとエラーになります。

```
ValueError: 19 is not a valid ISDBTuner.getDVBDeviceInfoFromDVBv5.<locals>.fe_delivery_system
```
https://github.com/DigitalDevices/dddvb/blob/ea8e877dca1cb9c1f5ca41e5cf86297d3cc08528/include/linux/dvb/frontend.h#L707
に isdb_scanner/tuner.py で定義されていない `SYS_DVBC2` が存在するためではないかと思います。
(修正しての動作確認はしていません)

**Comment by tsukumijima** [comment]
@daisukekoba ISDBScanner 1.1.5 にて修正されているのではと思います。
手元に DD Max M4 の実機がないため動作確認はできていませんが、ぜひ一度お試しください！
