### ISSUE TITLE
バージョン表示

### ISSUE THREAD

**Issue by eggplants** [tsukumijima/ISDBScanner#4]
現在、実際にコマンドを走らせることでしか、インストールされている本CLIのバージョンを確認できません。

```shellsession
$ isdb-scanner
=================================== ISDBScanner version 1.1.4 ===================================
Scanning ISDB-T (Terrestrial) channels...
...
```

`--help` で表示される内容に含まれているか、 `--version` のような、バージョンのみを表示するオプションがあると嬉しいです。

**Comment by tsukumijima** [comment]
@eggplants ISDBScanner 1.1.5 にて `--version` オプションを実装しました！
