### ISSUE TITLE
出力されるチャンネルリストの内容について

### ISSUE THREAD

**Issue by R-Django** [tsukumijima/ISDBScanner#8]
出力されるチャンネルリストの内容が下記の様に正しく整形されていないかのように見えます。
※ Mirakurun用に出力される ”channels_recpt1.yml” の一部です。

```
  - name: BS01/TS0
    type: BS
    channel: BS01_0
    isDisabled: false
  - name: BS01/TS1
    type: BS
    channel: BS01_1
    isDisabled: false
  - name: BS01/TS2
    type: BS
    channel: BS01_2
    isDisabled: false
  - name: BS03/TS0
    type: BS
    channel: BS03_0
    isDisabled: false
```

Channels.jsonの方は正しく取得できている様なのでチャンネルリストの出力時に何かしらの問題があるのかもしれませんが、エラーなどが表示されない為お力添えを頂きたく投稿させて頂きました。
[Channels.json](https://github.com/user-attachments/files/18001488/Channels.json)

次の方法でインストールしましたが、他に何か入れるべきパッケージなどありますでしょうか？

```
# x86_64 環境
sudo wget https://github.com/tsukumijima/ISDBScanner/releases/download/v1.2.0/isdb-scanner -O /usr/local/bin/isdb-scanner
sudo chmod +x /usr/local/bin/isdb-scanner
```

※私の環境は集合アンテナで地デジのチャンネルがパススルー方式の為、地デジチャンネルが一切取得できない環境です。

**Comment by tsukumijima** [comment]
> 下記の様に正しく整形されていないかのように見えます。

質問の意図をよく理解できていませんが、貼られている箇所自体に特にミスはないような気がします。何が問題なのかがよくわからないです。

また、集合住宅であっても CATV パススルーであれば通常の ISDB-T チャンネルで地上波を受信できるはずです。受信できないとしたら周波数変換パススルーか、ISDB-C チューナーが必要となるトランスモジュレーション方式と思われます。

**Comment by R-Django** [comment]
下記の様な形式になると勝手に思い込んでいたようです。
前述の様な形式でも差し支えないのですね。お恥ずかしいです。

```
- name: ＮＨＫＢＳ１
  type: BS
  channel: BS15_0
  serviceId: 101
  isDisabled: false
- name: ＮＨＫＢＳ１
  type: BS
  channel: BS15_0
  serviceId: 102
  isDisabled: true
- name: ＮＨＫＢＳプレミアム
  type: BS
  channel: BS3_1
  serviceId: 103
  isDisabled: true
- name: ＮＨＫＢＳプレミアム
  type: BS
  channel: BS3_1
  serviceId: 104
  isDisabled: true
- name: ＢＳ日テレ
  type: BS
  channel: BS13_0
  serviceId: 141
  isDisabled: false
- name: ＢＳ日テレ
  type: BS
  channel: BS13_0
  serviceId: 142
  isDisabled: true
```

御手数を掛け申し訳ありません。
Closeさせて頂きます。

**Comment by tsukumijima** [comment]
おっしゃるとおり、Mirakurun の channels.yml の name 項目は任意の値を入れるフィールドでして、視聴録画には影響しないという認識です。一般的なチャンネル名（サービス名）としては別途 services.json に EPG 取得時に取得されたサービス情報が書き込まれるという認識…
